# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Annotr < Formula
  desc "annotr - Fast local code commenting CLI"
  homepage "https://github.com/cloudboy-jh/annotr"
  version "0.2.7"
  license "MIT"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/cloudboy-jh/annotr/releases/download/v0.2.7/annotr_0.2.7_linux_amd64.tar.gz"
    sha256 "df0368600e2037a8f83740c5362a0eb17f7c0eb65d41068699db830d374a13b8"
    def install
      bin.install "annotr"
    end
  end
end
