# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Annotr < Formula
  desc "annotr - Fast local code commenting CLI"
  homepage "https://github.com/cloudboy-jh/annotr"
  version "0.2.23"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/cloudboy-jh/annotr/releases/download/v0.2.23/annotr_0.2.23_darwin_amd64.tar.gz"
    sha256 "fb0396d7594da9f517fb6b35d250405515a2cec07cf379cdde435d8d9fac0749"

    def install
      bin.install "annotr"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/cloudboy-jh/annotr/releases/download/v0.2.23/annotr_0.2.23_darwin_arm64.tar.gz"
    sha256 "8d8873019f614623ffed3f4da2ec392581df101f2c741ea19aafd2a3e88663e7"

    def install
      bin.install "annotr"
    end
  end
end
